version: '3'

services:
  db1:
    image: mysql:5.7
    volumes:
      - db_data1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db1
      MYSQL_USER: user1
      MYSQL_PASSWORD: pwd1
    ports:
       - "3306:3306"
      
volumes:
  db_data1:
